# Generated by Django 4.0.5 on 2022-07-18 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LPModel',
            fields=[
                ('learningpath_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'learningpaths',
            },
        ),
        migrations.CreateModel(
            name='LPStepsModel',
            fields=[
                ('lp_step_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('learningpath_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineerapp.lpmodel')),
            ],
            options={
                'db_table': 'learningpathsteps',
            },
        ),
    ]
