# Generated by Django 4.0.5 on 2022-07-18 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineerapp', '0002_lpmodel_lpstepsmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lpmodel',
            options={'ordering': ('learningpath_id', 'description')},
        ),
        migrations.AlterModelOptions(
            name='lpstepsmodel',
            options={'ordering': ('learningpath_id', 'lp_step_id')},
        ),
    ]
