# Generated by Django 4.0.5 on 2022-07-18 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineerapp', '0003_alter_lpmodel_options_alter_lpstepsmodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MIPModel',
            fields=[
                ('mip_id', models.AutoField(primary_key=True, serialize=False)),
                ('mip_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'mips',
            },
        ),
        migrations.RemoveField(
            model_name='lpstepsmodel',
            name='learningpath_id',
        ),
        migrations.AddField(
            model_name='lpstepsmodel',
            name='learningpath',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engineerapp.lpmodel'),
        ),
        migrations.AddField(
            model_name='lpmodel',
            name='mip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engineerapp.mipmodel'),
        ),
    ]
