# Generated by Django 4.0.5 on 2022-07-21 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineerapp', '0004_mipmodel_remove_lpstepsmodel_learningpath_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='engmodel',
            options={'ordering': ('engineer_id', 'name')},
        ),
        migrations.AlterField(
            model_name='lpstepsmodel',
            name='learningpath',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='engineerapp.lpmodel'),
        ),
        migrations.CreateModel(
            name='EngLPStepModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(db_index=True, default=False)),
                ('engineer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='engineerapp.engmodel')),
                ('lp_step', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='engineerapp.lpstepsmodel')),
            ],
            options={
                'db_table': 'lpstepcompletions',
                'ordering': ('engineer', 'lp_step'),
            },
        ),
        migrations.CreateModel(
            name='EngLPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='engineerapp.engmodel')),
                ('learningpath', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='engineerapp.lpmodel')),
            ],
            options={
                'db_table': 'engineer_learning_paths',
                'ordering': ('engineer', 'learningpath'),
            },
        ),
    ]
