# Generated by Django 4.0.5 on 2022-07-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineerapp', '0005_alter_engmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='englpmodel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='englpstepmodel',
            options={},
        ),
        migrations.AlterField(
            model_name='englpmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
